---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lena-was
spec:
  selector:
    matchLabels:
      type: lena-was
      app: app_name
  replicas: 2
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        type: lena-was
        app: app_name
        ver: "1"
    spec:
      containers:
      - name: lena-was
        image: docker.io/lenacloud/lena-cluster:1.3.1.0_2-ubuntu16.04-jdk8-openjdk
        imagePullPolicy: Always
        ports:
        - containerPort: 8180
        envFrom:
        - configMapRef:
            name: configmap-lena-was
        readinessProbe:
          tcpSocket:
            port: 8180
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 8180
          initialDelaySeconds: 20
          periodSeconds: 5
      terminationGracePeriodSeconds: 10
