---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lena-web
spec:
  selector:
    matchLabels:
      type: lena-web
      app: app_name
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        type: lena-web
        app: app_name
    spec:
      containers:
      - name: lena-web
        image: docker.io/lenacloud/lena-web:1.3.1n.0_2-ubuntu16.04-jdk8-openjdk
        imagePullPolicy: Always
        ports:
        - containerPort: 7180
        envFrom:
        - configMapRef:
            name: configmap-lena-web
        readinessProbe:
          tcpSocket:
            port: 7180
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 7180
          initialDelaySeconds: 20
          periodSeconds: 5
        command:
        - /bin/bash
        - "-c"
        - |
          INSTALL_PATH=/usr/local/lenaw/servers/webServer
          cat << EOF > $INSTALL_PATH/conf/extra/proxy/proxy_vhost_default.conf
          ProxyPassMatch $PROXY_MATCH_EXPRESSION_01 $PROXY_MATCH_ADDRESS_01
          ProxyPassMatch $PROXY_MATCH_EXPRESSION_02 $PROXY_MATCH_ADDRESS_02
          ProxyLENATTL 10
          EOF
          sed -i "/<\/VirtualHost>/i\Include \"$INSTALL_PATH\/conf\/extra\/proxy\/proxy_vhost_default.conf\"" \
          $INSTALL_PATH/conf/extra/vhost/vhost_default.conf
          /usr/local/lenaw/docker-entrypoint.sh
      terminationGracePeriodSeconds: 5

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-lena-web
data:
  PROXY_MATCH_EXPRESSION_01: "^/admin/.*$"
  PROXY_MATCH_ADDRESS_01: "http://windowsvmIP:8180"
  PROXY_MATCH_EXPRESSION_02: "^/.*$"
  PROXY_MATCH_ADDRESS_02: "http://lena-was.default.svc.cluster.local:8180"
  LOG_OUTPUT_TYPE: "console"

