---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lena-session
spec:
  selector:
    matchLabels:
      type: lena-session
  serviceName: lena-session
  replicas: 1
  template:
    metadata:
      labels:
        type: lena-session
    spec:
      containers:
      - name: lena-session
        image: docker.io/lenacloud/lena-session:1.3.1.0_2-jdk8-openjdk
        imagePullPolicy: Always
        ports:
        - containerPort: 5180
        envFrom:
        - configMapRef:
            name: configmap-lena-session
        readinessProbe:
          exec:
            command:
            - servers/sessionServer/health.sh
          initialDelaySeconds: 1
          periodSeconds: 3
        livenessProbe:
          exec:
            command:
            - servers/sessionServer/health.sh
          initialDelaySeconds: 10
          periodSeconds: 3
      terminationGracePeriodSeconds: 0

